version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./public:/var/www/html
